Repository boostcampwm-2024/refactor-web01-youQuiz, pull requests merged in 2025-01, with the labels that each got.

#1 [ FE ] - 닉네임 페이지 비지니스 로직, UI 분리
  packages/client/src/pages/nickname/hooks/useNicknameSubmit.ts
  packages/client/src/pages/nickname/index.tsx
  packages/client/src/pages/nickname/ui/NicknameForm.tsx
Labels: 🤖 Refactor

#3 [FE] - 메인 페이지 비즈니스 로직 및 컴포넌트 분리
  packages/client/src/pages/main/hooks/useCheckPincodePossible.ts
  packages/client/src/pages/main/hooks/useCheckPincodeStatus.ts
  packages/client/src/pages/main/index.tsx
  packages/client/src/pages/main/ui/MainPageBackground.tsx
Labels: 🤖 Refactor

#5 [FE] - 리더보드 페이지 컴포넌트 리팩토링
  packages/client/src/pages/leaderboard/index.lazy.tsx
  packages/client/src/pages/leaderboard/index.tsx
  packages/client/src/pages/leaderboard/model/hooks/useLeaderboard.ts
  packages/client/src/pages/leaderboard/ui/ConfettiBackground.tsx
  packages/client/src/pages/leaderboard/ui/PlayerList.tsx
  packages/client/src/pages/leaderboard/ui/TopPlayer.tsx
  packages/client/src/pages/quiz-session/ui/QuizHeader.tsx
  packages/client/src/pages/quiz-wait/ui/UserGridItem.tsx
  packages/client/src/shared/constants/character.ts
Labels: 🤖 Refactor

#4 [FE] - 퀴즈 생성 컴포넌트 리팩토링
  packages/client/src/pages/quiz-create/contexts/quizContext.tsx
  packages/client/src/pages/quiz-create/contexts/quizContext.types.ts
  packages/client/src/pages/quiz-create/contexts/useQuizContext.ts
  packages/client/src/pages/quiz-create/index.tsx
  packages/client/src/pages/quiz-create/ui/QuizActions.tsx
  packages/client/src/pages/quiz-create/ui/QuizCreateSection.tsx
  packages/client/src/pages/quiz-create/ui/QuizNavigatioin.tsx
  packages/client/src/shared/ui/input-box/InputBox.tsx
Labels: 🤖 Refactor

#6 [FE] - 퀴즈 마스터 세션 컴포넌트 리팩토링, ContextAPI 도입
  packages/client/src/pages/quiz-master-session/context/quizContext.tsx
  packages/client/src/pages/quiz-master-session/hooks/useQuizContext.ts
  packages/client/src/pages/quiz-master-session/hooks/useStatisticsState.ts
  packages/client/src/pages/quiz-master-session/index.lazy.tsx
  packages/client/src/pages/quiz-master-session/index.tsx
  packages/client/src/pages/quiz-master-session/ui/AnswerChart.tsx
  packages/client/src/pages/quiz-master-session/ui/QuizMasterHeader.tsx
  packages/client/src/pages/quiz-master-session/ui/RightPanel.tsx
  packages/client/src/pages/quiz-master-session/ui/Statistics.tsx
  packages/client/src/pages/quiz-master-session/ui/StatisticsLayout.tsx
Labels: ✨ Feature, 🤖 Refactor

#9 [FE] - 폰트 로딩 지연을 줄여 LCP, FCP 개선
  packages/client/index.html
  packages/client/src/font.css
  packages/client/src/index.css
  packages/client/src/pages/quiz-list/ui/ClassItem.tsx
  packages/client/src/shared/api/classes/index.ts
  packages/client/src/shared/api/quizzes/index.ts
  packages/client/src/shared/assets/fonts/Pretendard-Black.woff2
  packages/client/src/shared/assets/fonts/Pretendard-Bold.subset.woff2
  packages/client/src/shared/assets/fonts/Pretendard-Bold.woff2
  packages/client/src/shared/assets/fonts/Pretendard-ExtraBold.woff2
  packages/client/src/shared/assets/fonts/Pretendard-ExtraLight.woff2
  packages/client/src/shared/assets/fonts/Pretendard-Light.woff2
  packages/client/src/shared/assets/fonts/Pretendard-Medium.subset.woff2
  packages/client/src/shared/assets/fonts/Pretendard-Medium.woff2
  packages/client/src/shared/assets/fonts/Pretendard-Regular.subset.woff2
  packages/client/src/shared/assets/fonts/Pretendard-Regular.woff2
  packages/client/src/shared/assets/fonts/Pretendard-SemiBold.woff2
  packages/client/src/shared/assets/fonts/Pretendard-Thin.woff2
  packages/client/src/shared/hooks/quizzes.ts
Labels: 🤖 Refactor

#10 [FE] - Light House SEO 개선
  packages/client/index.html
  packages/client/public/robots.txt
Labels: 🤖 Refactor

#11 [Refactor] 도메인 주도 개발을 위한 퀴즈 관련 리패키징
  packages/server/src/module/game/games/game.service.ts
  packages/server/src/module/quiz/application/quiz.service.ts
  packages/server/src/module/quiz/domain/entities/choice.entity.ts
  packages/server/src/module/quiz/domain/entities/class.entity.ts
  packages/server/src/module/quiz/domain/entities/quiz.entity.ts
  packages/server/src/module/quiz/infrastructure/choice.repository.ts
  packages/server/src/module/quiz/infrastructure/class.repository.ts
  packages/server/src/module/quiz/infrastructure/quiz.repository.ts
  packages/server/src/module/quiz/presentation/dto/request/create-choice.request.dto.ts
  packages/server/src/module/quiz/presentation/dto/request/create-class.request.dto.ts
  packages/server/src/module/quiz/presentation/dto/request/create-quiz.request.dto.ts
  packages/server/src/module/quiz/presentation/dto/request/create-quizlist.request.dto.ts
  packages/server/src/module/quiz/presentation/dto/request/update-choice.request.dto.ts
  packages/server/src/module/quiz/presentation/dto/request/update-class.request.dto.ts
  packages/server/src/module/quiz/presentation/dto/request/update-quiz.request.dto.ts
  packages/server/src/module/quiz/presentation/dto/request/update-quizlist.request.dto.ts
  packages/server/src/module/quiz/presentation/dto/response/choice.response.dto.ts
  packages/server/src/module/quiz/presentation/dto/response/create-class.response.dto.ts
  packages/server/src/module/quiz/presentation/dto/response/get-class.response.dto.ts
  packages/server/src/module/quiz/presentation/dto/response/quiz.response.dto.ts
  packages/server/src/module/quiz/presentation/quiz.controller.ts
  packages/server/src/module/quiz/quiz.module.ts
  packages/server/src/module/quiz/utils/quiz-type.enum.ts
Labels: 🤖 Refactor

#12 [BE] GameGateway 비즈니스 로직 제거 및 서비스 레이어 분리
  packages/server/src/module/game/application/game.service.ts
  packages/server/src/module/game/constants/game-events.enum.ts
  packages/server/src/module/game/domain/services/game.quiz.service.ts
  packages/server/src/module/game/domain/services/game.ranking.service.ts
  packages/server/src/module/game/domain/services/game.state.service.ts
  packages/server/src/module/game/domain/services/game.user-info.service.ts
  packages/server/src/module/game/game.module.ts
  packages/server/src/module/game/games/game.gateway.ts
  packages/server/src/module/game/games/game.service.ts
  packages/server/src/module/game/interfaces/GameInfo.ts
  packages/server/src/module/game/interfaces/ParticipantInfo.ts
  packages/server/src/module/game/interfaces/QuizStatistics.ts
  packages/server/src/module/game/presentation/dto/request/emoji.request.dto.ts
  packages/server/src/module/game/presentation/dto/request/end-quiz.request.dto.ts
  packages/server/src/module/game/presentation/dto/request/leaderboard.request.dto.ts
  packages/server/src/module/game/presentation/dto/request/master-entry.request.dto.ts
  packages/server/src/module/game/presentation/dto/request/message.request.dto.ts
  packages/server/src/module/game/presentation/dto/request/nickname.request.dto.ts
  packages/server/src/module/game/presentation/dto/request/participant-entry.request.dto.ts
  packages/server/src/module/game/presentation/dto/request/show-quiz.request.dto.ts
  packages/server/src/module/game/presentation/dto/request/show-ranking.request.dto.ts
  packages/server/src/module/game/presentation/dto/request/start-quiz.request.dto.ts
  packages/server/src/module/game/presentation/dto/request/submit-answer.request.dto.ts
  packages/server/src/module/game/presentation/game.controller.ts
  packages/server/src/module/game/presentation/game.gateway.ts
Labels: 🤖 Refactor

#13 [FE] - 소켓 테스트를 위한 `Tester` 클래스 생성
  packages/client/src/shared/libs/tests/socket-test.ts
Labels: ✨ Feature, ✅ Test

#18 [FE] - `useLeaderboard` 커스텀 훅에 대한 테스트 코드 작성
  packages/client/src/tests/leaderboard/useLeaderboard.test.tsx
Labels: ✅ Test
